//! Regenerates `apps/mobile/src/core/nativeCoreTypes.ts` from the `core_*`
//! Tauri commands' own Rust types — `View`/`Intent`/`CoreEvent` and everything
//! they reference (down to `protocol`'s wire vocabulary) are the source of
//! truth; this file is a build artifact, never hand-edited.
//!
//! Run it to regenerate: `cargo test --features native-core --test
//! gen_ts_bindings -- --ignored` (see `codedeck gen-protocol-types` for the
//! Docker-wrapped form). CI runs the SAME command then `git diff --exit-code`s
//! the output — a Rust type change that isn't followed by a regeneration
//! fails the build, the same anti-drift shape as `crates/protocol`'s
//! fixture-corpus check.
//!
//! `#[ignore]`d rather than a normal test: it writes to the working tree,
//! which a plain `cargo test` run should never do as a side effect. The
//! actual `Builder` lives in `corebridge::ts_bindings_builder` — see its own
//! doc comment for why it can't live here.
#![cfg(feature = "native-core")]

use codedeck_mobile_lib::corebridge::ts_bindings_builder;

#[test]
#[ignore = "writes ../../src/core/nativeCoreTypes.ts — run explicitly to regenerate"]
fn gen_ts_bindings() {
    ts_bindings_builder()
        .export(
            specta_typescript::Typescript::default()
                .header(
                    "// GENERATED by `cargo test -p codedeck-mobile --features native-core --test gen_ts_bindings -- --ignored` — do not hand-edit.\n\
                     // Source of truth: crates/protocol + crates/client-core + crates/client-runtime's View/Intent/CoreEvent types.\n",
                ),
            "../src/core/nativeCoreTypes.ts",
        )
        .expect("export TS bindings");
}
