//! Regenerates `packages/agent-host/src/generated/protocol.ts` from this
//! crate's types — the agent host's side of the driver protocol is a build
//! artifact of the Rust definitions, never hand-edited.
//!
//! Run it to regenerate: `cargo test -p agent-protocol --test
//! gen_ts_bindings -- --ignored`. CI runs the same command and then
//! `git diff --exit-code`s the output, so a type change that is not followed
//! by a regeneration fails the build.
//!
//! `#[ignore]`d because it writes to the working tree, which a plain
//! `cargo test` should never do as a side effect.

use agent_protocol::{BridgeFrame, HostFrame};

const OUT: &str = "../../packages/agent-host/src/generated/protocol.ts";

#[test]
#[ignore = "writes packages/agent-host/src/generated/protocol.ts — run explicitly to regenerate"]
fn gen_ts_bindings() {
    let types = specta::Types::default().register::<BridgeFrame>().register::<HostFrame>();
    specta_typescript::Typescript::default()
        .header(
            "// GENERATED by `cargo test -p agent-protocol --test gen_ts_bindings -- --ignored` — do not hand-edit.\n\
             // Source of truth: crates/agent-protocol (and the crates/protocol types it references).\n",
        )
        .export_to(OUT, &types, specta_serde::PhasesFormat)
        .expect("export TS bindings");
}
