//! `quick_prompts` store (CDX-049) — user-defined labeled prompt shortcuts.
//! Port of the pure half of `apps/mobile/src/core/stores/quickPrompts.ts`.
//!
//! The list renders as a tappable bar above the session input; a tap INSERTS
//! the prompt text into the draft (never auto-sends). Persistence is the
//! runtime's (KV port, save after every successful mutation, garbage-tolerant
//! hydrate); the store here is pure — the id for a new prompt is generated by
//! the runtime and passed in, like `outbox::new_input`.

use serde::{Deserialize, Serialize};

pub const QUICK_PROMPTS_STORAGE_KEY: &str = "quickPrompts";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct QuickPrompt {
    pub id: String,
    pub label: String,
    pub text: String,
}

/// Garbage-tolerant hydrate: bad JSON, a non-array, or a malformed entry each
/// yield an empty list / a dropped entry rather than an error. An entry needs a
/// non-empty string `id` and string `label` + `text`.
pub fn hydrate_quick_prompts(raw: Option<&str>) -> Vec<QuickPrompt> {
    let Some(raw) = raw else {
        return vec![];
    };
    let Ok(value) = serde_json::from_str::<serde_json::Value>(raw) else {
        return vec![];
    };
    let Some(arr) = value.as_array() else {
        return vec![];
    };
    arr.iter()
        .filter_map(|item| {
            let obj = item.as_object()?;
            let id = obj.get("id")?.as_str()?;
            if id.is_empty() {
                return None;
            }
            let label = obj.get("label")?.as_str()?;
            let text = obj.get("text")?.as_str()?;
            Some(QuickPrompt {
                id: id.to_string(),
                label: label.to_string(),
                text: text.to_string(),
            })
        })
        .collect()
}

pub fn serialize_quick_prompts(prompts: &[QuickPrompt]) -> String {
    serde_json::to_string(prompts).expect("QuickPrompt list serializes")
}

/// The quick-prompts store as pure state. Every mutator returns `true` when it
/// changed the list — the runtime persists [`serialize_quick_prompts`] then.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct QuickPromptsState {
    pub prompts: Vec<QuickPrompt>,
}

impl QuickPromptsState {
    /// Seed from a hydrated list on boot.
    pub fn from_hydrated(prompts: Vec<QuickPrompt>) -> Self {
        Self { prompts }
    }

    /// Append a prompt. `id` is the runtime's generated id. `label`/`text` are
    /// trimmed; both must be non-empty or the call is a no-op.
    pub fn add_prompt(&mut self, id: &str, label: &str, text: &str) -> bool {
        let label = label.trim();
        let text = text.trim();
        if label.is_empty() || text.is_empty() {
            return false;
        }
        self.prompts.push(QuickPrompt {
            id: id.to_string(),
            label: label.to_string(),
            text: text.to_string(),
        });
        true
    }

    /// Edit an existing prompt. Trims; rejects an empty field; unknown id is a
    /// no-op.
    pub fn update_prompt(&mut self, id: &str, label: &str, text: &str) -> bool {
        let label = label.trim();
        let text = text.trim();
        if label.is_empty() || text.is_empty() {
            return false;
        }
        let Some(prompt) = self.prompts.iter_mut().find(|p| p.id == id) else {
            return false;
        };
        prompt.label = label.to_string();
        prompt.text = text.to_string();
        true
    }

    /// Remove a prompt. Unknown id is a no-op.
    pub fn remove_prompt(&mut self, id: &str) -> bool {
        let before = self.prompts.len();
        self.prompts.retain(|p| p.id != id);
        self.prompts.len() != before
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn qp(id: &str, label: &str, text: &str) -> QuickPrompt {
        QuickPrompt {
            id: id.to_string(),
            label: label.to_string(),
            text: text.to_string(),
        }
    }

    #[test]
    fn add_update_remove_with_trimming_and_empty_field_rejection() {
        let mut s = QuickPromptsState::default();

        assert!(s.add_prompt("qp-1", "  Continue  ", "  Keep going with the plan.  "));
        assert_eq!(s.prompts, vec![qp("qp-1", "Continue", "Keep going with the plan.")]);

        // blank label or text never creates an entry
        assert!(!s.add_prompt("qp-2", "   ", "text"));
        assert!(!s.add_prompt("qp-3", "label", "   "));
        assert_eq!(s.prompts.len(), 1);

        assert!(s.update_prompt("qp-1", "Go on", "Continue exactly where you left off."));
        assert_eq!(
            s.prompts[0],
            qp("qp-1", "Go on", "Continue exactly where you left off.")
        );
        assert!(!s.update_prompt("qp-1", "", "x")); // rejected, unchanged
        assert_eq!(s.prompts[0].label, "Go on");
        assert!(!s.update_prompt("nope", "a", "b")); // unknown id → no-op
        assert_eq!(s.prompts.len(), 1);

        assert!(s.remove_prompt("qp-1"));
        assert!(s.prompts.is_empty());
        assert!(!s.remove_prompt("qp-1")); // second remove is a no-op
    }

    #[test]
    fn round_trips_through_serialize_then_hydrate() {
        let mut s = QuickPromptsState::default();
        s.add_prompt("qp-1", "Tests", "Run the whole test suite and report counts.");
        s.add_prompt("qp-2", "Ship", "Commit with a conventional message.");
        s.remove_prompt("qp-1");

        let raw = serialize_quick_prompts(&s.prompts);
        let rebooted = hydrate_quick_prompts(Some(&raw));
        assert_eq!(
            rebooted,
            vec![qp("qp-2", "Ship", "Commit with a conventional message.")]
        );

        let s2 = QuickPromptsState::from_hydrated(rebooted);
        assert_eq!(s2.prompts.len(), 1);
    }

    #[test]
    fn hydrate_tolerates_garbage() {
        assert!(hydrate_quick_prompts(None).is_empty());
        assert!(hydrate_quick_prompts(Some("not json")).is_empty());
        assert!(hydrate_quick_prompts(Some(r#"{"a":1}"#)).is_empty());
        assert_eq!(
            hydrate_quick_prompts(Some(
                r#"[
                    {"id":"ok","label":"L","text":"T"},
                    {"id":"","label":"no-id","text":"x"},
                    {"id":"no-text","label":"x"},
                    "garbage",
                    null
                ]"#
            )),
            vec![qp("ok", "L", "T")]
        );
    }
}
